# Generated by Django 2.0 on 2018-01-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctsapp.Team'),
        ),
    ]
