# Generated by Django 2.0 on 2018-01-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0002_auto_20180130_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='ort_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctsapp.Ort'),
        ),
    ]
