# Generated by Django 2.0 on 2018-01-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0003_auto_20180130_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='ort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctsapp.Ort'),
        ),
    ]
