# Generated by Django 2.0 on 2018-01-31 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0005_auto_20180131_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spielerentdecktspot',
            name='id',
        ),
        migrations.AlterField(
            model_name='spielerbewertetspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctsapp.Spot'),
        ),
    ]
