# Generated by Django 2.0 on 2018-01-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0006_auto_20180131_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='ctsapp.Spot'),
        ),
    ]
