# Generated by Django 2.0 on 2018-01-31 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0007_auto_20180131_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielerbewertetspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
