# Generated by Django 2.0 on 2018-02-02 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0008_auto_20180131_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielerbewertetspot',
            name='bewertung_text',
            field=models.CharField(default='asd', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spielerbewertetspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spielerbewertetspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctsapp.Spot'),
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctsapp.Spot'),
        ),
    ]
