# Generated by Django 2.0 on 2018-02-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0009_auto_20180202_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spielerbewertetspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='ctsapp.Spot'),
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='ctsapp.Spot'),
        ),
    ]
