# Generated by Django 2.0 on 2018-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0010_auto_20180202_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='gamemaster_flag',
            field=models.BooleanField(default=False),
        ),
    ]
