# Generated by Django 2.0 on 2018-02-26 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0011_auto_20180226_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spieler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'gamemaster',
            },
        ),
        migrations.CreateModel(
            name='GamemasterVerwaltetSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('aktion', models.IntegerField(blank=True, null=True)),
                ('spieler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctsapp.Spot')),
            ],
            options={
                'managed': True,
                'db_table': 'gamemaster_verwaltet_spot',
            },
        ),
        migrations.AlterField(
            model_name='spielerentdecktspot',
            name='spieler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gamemasterverwaltetspot',
            unique_together={('spieler_id', 'spot_id')},
        ),
    ]
