# Generated by Django 2.0 on 2018-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsapp', '0012_auto_20180226_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='punktzahl',
            field=models.IntegerField(blank=True),
        ),
    ]
